# This is a basic workflow to help you get started with Actions

name: Generates Pdf from MD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update and install all packages
        run: |
          echo Updating and installing packages
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y pandoc texlive-latex-recommended texlive-latex-extra texlive-xetex

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Converting files
          mkdir -p pdf
          pandoc -s notes.md -o pdf/notes.tex --pdf-engine=xelatex
          pdflatex  -interaction nonstopmode -output-directory pdf/ pdf/notes.tex
